#ifndef TAG_H
#define TAG_H
class Tag{
public:
	static const int IDEN, INTCON,CHARCON,STRCON,CONSTTK,INTTK,CHARTK,VOIDTK,MAINTK,IFTK,
		ELSETK,DOTK,WHILETK,FORTK,SCANFTK,PRINTFTK,RETURNTK,PLUS,MINU,MULT,DIV,
		LSS,LEQ,GRE,GEQ,EQL,NEQ,ASSIGN,SEMICN,COMMA,PERIOD,QMARK,DQMARK,LPARENT,
		RPARENT,LBRACK,RBRACK,LBRACE,RBRACE,ILLEGALNUM,ILLEGALCHA,ILLEGALSTR;
};
#endif